time_between_ticks = 250

[[sources]]
name = "my-counter-source"
type = "counter"
schedule = "* * * * * * *"
pipe = ["my-keymap->my-console-sink"]
key_name = "old_key"

[[sinks]]
name = "my-console-sink"
type = "console"
prefix = "::"

[[processors]]
name = "my-keymap"
type = "keymap"
from_key = "old_key"
to_key = "new_key"
