[package]
name = "feed-plumber-plugin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sys-feed-plumber-plugin = { path = "../sys-feed-plumber-plugin" }
cstr = "0.2.11"